### PR TITLE
Fix argmin and argmax

### LINKED ISSUE #97: `argmax` returns incorrect results
SentinelArrays incorrectly implements [`argmax`](https://docs.julialang.org/en/v1/base/collections/#Base.argmax) for `ChainedVector`s. It returns the maximum value, rather than its index. 

```julia
julia> using SentinelArrays

julia> arrays = [
         [18, 70, 92, 15, 65],
         [25, 14, 95, 54, 57]
       ];

julia> cv = ChainedVector(arrays);

julia> argmax(cv)
95

julia> argmax(collect(cv))
8
```

The implementation is [here](https://github.com/JuliaData/SentinelArrays.jl/blob/fa840f994ae821d921a9973fbd5e244d35102b1c/src/chainedvector.jl#L838) and is [tested](https://github.com/JuliaData/SentinelArrays.jl/blob/fa840f994ae821d921a9973fbd5e244d35102b1c/test/chainedvector.jl#L253), though the test only tests a simple special case for which the values and indices are exactly equal.

This issue was initially filed [upstream](https://github.com/JuliaData/CSV.jl/issues/1128).

### PR DESCRIPTION
**Pull request by gdalle**
Draft PR to fix #97

How do we add proper tests for this in the least disruptive way?

### CODE REVIEW

File: src/chainedvector.jl [hunk 1]
```diff
@@ -825,8 +825,8 @@ function findXwithfirst(comp, f, x, y, i)
     for A in x.arrays
         for y′ in A
             y′′ = f(y′)
+            i = ifelse(comp(y′′, y), i′, i)  # do this before y possibly changes!!!
```
Comment (mkitti) [inline src/chainedvector.jl:828]: Why run `comp(y′′, y)` twice in the first place?

Comment (gdalle) [reply src/chainedvector.jl:828]: That was already there when I arrived, but I can fix it

**Comment by mkitti** [comment]
I'm working on more tests in #99

**Comment by Seelengrab** [comment]
Might I suggest an approach based on property based testing? A good one here would be

```julia
isargmax_maximum(cv) = cv[argmax(cv)] == maximum(cv)
```

(substitute with `argmin`/`minimum` respectively for the minimum case.)

This catches the problem immediately, if used with random data. Such a property can also be used automatically with (shameless plug) [Supposition.jl](https://github.com/Seelengrab/Supposition.jl):

```julia
julia> using Supposition

julia> data_vector = Data.Vectors(Data.Integers{UInt8}(); max_size=100);

julia> vecs = Data.Vectors(data_vector; min_size=1, max_size=10);

julia> chainedvecs = map(vecs) do vs
           all(isempty, vs) && reject!()
           ChainedVector(vs)
       end;

julia> isargmax_maximum(cv) = cv[argmax(cv)] == maximum(cv)

julia> @check db=false isargmax_maximum(chainedvecs);
┌ Error: Property errored!
│   Description = "isargmax_maximum"
│   arg_1 =
│    1-element ChainedVector{UInt8, Vector{UInt8}}:
│     0x00
│   exception =
│    BoundsError: attempt to access 1-element ChainedVector{UInt8, Vector{UInt8}} at index [0x00]
│    Stacktrace:
│     [1] throw_boundserror(A::ChainedVector{UInt8, Vector{UInt8}}, I::Tuple{UInt8})
│       @ Base ./essentials.jl:14
│     [2] checkbounds
│       @ ./abstractarray.jl:699 [inlined]
│     [3] getindex
│       @ ~/.julia/packages/SentinelArrays/1kRo4/src/chainedvector.jl:94 [inlined]
│     [4] isargmax_maximum(cv::ChainedVector{UInt8, Vector{UInt8}})
│       @ Main ./REPL[39]:1
└ @ Supposition ~/Documents/projects/Supposition.jl/src/testset.jl:287
Test Summary:    | Error  Total  Time
isargmax_maximum |     1      1  0.7s
```

Of course, generating some random data and testing that would be sufficient for catching the problem. Supposition.jl just tries to give a minimal example, in this case `ChainedVector([[0]])`.

**Comment by mkitti** [comment]
I found another discrepancy.

```
julia> c = ChainedVector([[7, 21, 31], [45], [53, 53]])
6-element ChainedVector{Int64, Vector{Int64}}:
  7
 21
 31
 45
 53
 53

julia> findmax(c)
(53, 6)

julia> findmax(collect(c))
(53, 5)
```

**Comment by gdalle** [comment]
Did you try to see if my fix resolves it?

I agree that adding a flurry of tests, property testing and other stuff seems like a good idea in the medium run. My goal with this PR is simpler: there was a thing that was badly broken, it is now fixed with a minimal set of tests. I don't thing merging this and thinking about future, better tests are two incompatible actions.

**Comment by mkitti** [comment]
I agree that these are orthogonal approaches. I have merged this branch into mine on #99.

The question is what is the problem identified in #97 ? To me the problem is that testing is severely insufficient.

**Comment by gdalle** [comment]
And that `argmax` is wrong. My PR only resolves the latter

File: test/chainedvector.jl [hunk 2]
```diff
@@ -284,6 +284,17 @@
...
+    # https://github.com/JuliaData/SentinelArrays.jl/issues/97
+    x = ChainedVector([[18, 70, 92, 15, 65], [25, 14, 95, 54, 57]])
+    @test findmax(x) == (95, 8)
+    @test findmin(x) == (14, 7)
+    @test argmax(x) == 8
+    @test argmin(x) == 7
+    @test findmax(inv, x) == (inv(14), 7)
+    @test findmin(inv, x) == (inv(95), 8)
+    @test argmax(inv, x) == 14
+    @test argmin(inv, x) == 95
```
Comment (Seelengrab) [inline test/chainedvector.jl:296]:
```suggestion
    @test let (val, idx) = findmax(x)
         max_val = maximum(x)
         val == max_val == x[idx]
    end
    @test let (val, idx) = findmin(x)
         min_val = minimum(x)
         val == min_val == x[idx]
    end
    @test x[argmax(x)] == maximum(x)
    @test x[argmin(x)] == minimum(x)
    @test let (val, idx) = findmax(inv, x)
         max_val = maximum(inv, x)
         val == max_val == inv(x[idx])
    end
    @test let (val, idx) = findmin(inv, x)
         min_val = minimum(inv, x)
         val == min_val == inv(x[idx])
    end
    @test x[argmax(inv, x)] == maximum(inv, x)
    @test x[argmin(inv, x)] == minimum(inv, x)
```

IMO writing it like this would be a bit more robust against changing `x` in the future and forgetting to change the hardcoded data. This also ends up testing that `argmax` actually has to return an index, and not just the right number for this test case :)

Comment (mkitti) [reply test/chainedvector.jl:296]: I'll adopt this in #99

**Review by quinnj — APPROVED** [review]
Thanks @gdalle!

**Comment by Moelf** [comment]
can we make a release?
